# Site settings
title: safrazik
tagline: "crazy enough to create enough"
description: ""
baseurl: ""
url: "http://safrazik.github.io"
disqus_enabled: true
disqus_shortname: safrazik

# Build settings
markdown: redcarpet
permalink: pretty
sass:
    sass_dir: _scss