# Site settings
title: safrazik
tagline: ""
description: ""
baseurl: ""
url: "http://safrazik.github.io"
disqus_shortname: safrazik

# Build settings
markdown: kramdown
permalink: pretty
sass:
    sass_dir: _scss